### ISSUE TITLE
Consider using newtypes for trace and span ID types

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-rust#11]

**Comment by Monkeyanator** [comment]
Hi, I'm planning to take this on as a first issue 😊

To be clear, is there a reason we want trace ID and span ID to follow the`newtype` pattern rather than using a type alias? I understand that `newtype` comes with stricter guarantees on what can be passed where, but are those guarantees desired in this case?

**Comment by jtescher** [comment]
@Monkeyanator great you want to take on this issue! I think we're leaning toward newtypes here to hide the implementation and the safety guarantees seem like they are a good tradeoff in this case

**Comment by jtescher** [comment]
Resolved in #73
