### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1490]
---- logs::log_processor::tests::test_default_batch_config_adheres_to_specification stdout ----
thread 'logs::log_processor::tests::test_default_batch_config_adheres_to_specification' panicked at opentelemetry-sdk/src/logs/log_processor.rs:504:9:
assertion `left == right` failed
  left: 2.046s
 right: 30s
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    logs::log_processor::tests::test_default_batch_config_adheres_to_specification

**Comment by lalitb** [comment]
where is this reported? If locally, ensure that the env variables OTEL_BLRP_EXPORT_TIMEOUT / OTEL_BLRP_EXPORT_TIMEOUT_MILLIS are not already set.

**Comment by cijothomas** [comment]
Its in CI only : https://github.com/open-telemetry/opentelemetry-rust/actions/runs/7642309644/job/20821630333?pr=1488#step:7:1138

**Comment by lalitb** [comment]
The env-variable is being temporality set in one of these tests - https://github.com/open-telemetry/opentelemetry-rust/blob/16fd1abb879c48fdb9c87e65e9aaabbe1afdf3bc/opentelemetry-sdk/src/logs/log_processor.rs#L610

So multiple tests running in parallel can cause conflict, and one test reuse the env-variable set through another test. Probably good to run them sequentially - https://doc.rust-lang.org/book/ch11-02-running-tests.html

**Comment by mattbodd** [comment]
I'm interested in working on this issue if it's still available

**Comment by cijothomas** [comment]
> I'm interested in working on this issue if it's still available

Go for it!
Thank you!

**Comment by mattbodd** [comment]
As @lalitb mentioned, we hit this issue when running tests in parallel since we don't synchronize read/write access to environment variables. The options I see are to:
* Run tests sequentially
* Use a global lock to synchronize potentially concurrent reads/writes

Running tests sequentially is the simplest approach and is a fool-proof way to ensure tests don't clobber each other, but our unit test execution time will go up. Using a global lock potentially adds a step when writing tests and leaves room for error when authoring tests but allows fine grained controlled of which tests run in parallel and which run sequentially which would help keep test execution time down.

Does anyone have preferences between these two approaches and/or have other ideas?

**Comment by mattbodd** [comment]
Something like [serial_test](https://crates.io/crates/serial_test) would make synchronization relatively straightforward

**Comment by lalitb** [comment]
I like the idea of using `serial_test` if we can find these conflicting tests and make them serial with it. Do we know how much the time increases if all are made serial?

**Comment by mattbodd** [comment]
With the proposed changes in https://github.com/open-telemetry/opentelemetry-rust/pull/1496, I don't see any change in test execution time on my local dev machine (to the 1/100th of a second).
