### ISSUE TITLE
How should spans be stored for in-process propagation purposes?

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-rust#15]
Propagating spans across different components can be a pain, especially if not all components currently "expect" a span.

Some sort of context-local variable (along the lines of [Python's contextvars](https://www.python.org/dev/peps/pep-0555/)) might be useful here.

**Comment by hawkw** [comment]
IMO, this should be the responsibility of higher-level crates that depend on `opentelemetry-rust`; for example, [`tracing-opentelemetry`](https://github.com/jtescher/tracing-opentelemetry) provides an implementation that uses the `tracing` crate to propagate span contexts.

Rust doesn't have anything like the Python `contextvars` you mentioned in the language or standard library, but there are various approaches in third-party crates. Some of these are specific to a runtime or use-case, while others might be generally applicable. Personally, I don't think it makes sense for the OpenTelemetry bindings in this crate to have an opinion on how to propagate contexts; different approaches might make sense in different use-cases. For example, if this crate _did_ have a baked-in solution to this, I suspect the `tracing-opentelemetry` crate wouldn't be able to use it.

Alternatively, we could provide an _interface_ rather than an implementation in this crate. If there was a trait for propagating span contexts, then other libraries could implement that interface.

**Comment by iredelmeier** [comment]
@hawkw I agree with you re: keeping the main crate unopinionated. Providing an interface sounds good to me!

However, I think providing at least one async-compatible implementation of that interface may be valuable - possibly in its own subcrate.

**Comment by hawkw** [comment]
> However, I think providing at least one async-compatible implementation of that interface may be valuable - possibly in its own subcrate.

"async-compatible" complicates this a bit — I think the approach used by the [`tracing-futures`][1] crate of providing [a combinator that sets a thread-local context when a future is polled][2] is really the only way to do this that will work across all executor implementations without requiring APIs that tie us to a specific async runtime. We could definitely provide our own _sui generis_ implementation of this if you think that's a good idea.

[1]: https://docs.rs/tracing-futures/0.1.1/tracing_futures/
[2]: https://github.com/tokio-rs/tracing/blob/4c1a69d9e43a0c87dca60c649a2e949b3dca8b41/tracing-futures/src/lib.rs#L242-L246

**Comment by iredelmeier** [comment]
Definitely not 100% sure that it would be a good idea! However, propagation has been one of the biggest hurdles to adoption for other languages, so I think we need _some_ way of making it at least easy-ish.

**Comment by jtescher** [comment]
Currently the `mark_span_as_active` API is opt-in, but it does have quite a few rough edges, hence #21. `tracing-opentelemetry` works just fine without using it as @hawkw mentioned.

**Comment by iredelmeier** [comment]
[From 12/03/19 SIG meeting]

The current scope management likely doesn't work with Futures.

**Comment by jtescher** [comment]
Closing this for now as the async solution is working. Can re-open if we want to consider alternatives.
