### ISSUE TITLE
AttributeSet in the OpenTelemetry API

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#1508]
https://github.com/open-telemetry/opentelemetry-rust/pull/1421 allowed pre-creation of `AttributeSet` for scenarios requiring high performance. This also moved `AttributeSet` to the opentelemetry api. This has an _undesired/unintended_ side effect: The entire cost of creating `AttributeSet`is now paid in the API itself (like sort/hash/de-duplication), making it impossible to do optimizations in the SDK, as the perf hit is already paid in the API itself. 

This violates the core OTel requirement that the overhead of using the OTel API should be zero/close-to-zero, without an SDK configured. Because right now, even without an SDK configured, the OTel API does the `AttributeSet` creation which is a far from the zero/close-to-zero overhead. i.e the [NoOp ](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/noop.md) implementation is broken.

This is similar to https://github.com/open-telemetry/opentelemetry-rust/issues/1189, but this is much more serious due to the perf hit.

Need to find a way to achieve the intended perf gains, but yet move off entire `AttributeSet` creation to the actual SDK. Will discuss some ideas in the next community meeting.

cc : @lalitb @KallDrexx

**Comment by KallDrexx** [comment]
This feels like an arbitrary requirement to me.  How many real users are 
1. Using opentelemetry-rust with the No-op implementation
2. Using it in a performance critical system where the impact is noticeable.

Is this just a theoretical concern or has this really been a legitimate issue in the past?  

We could make the `AttributeSet` lazily create the `InnerAttributeSet` only when actually called upon.  This would require either a `Mutex` or `RwLock` to ensure we can handle concurrent access to the attribute set, which would incur extra costs.  It will also require some complex lifetime management, because we can no longer consume the `Into<AttributeSet>` iterator immediately, and thus a `&[KeyValue]` needs to live long enough until the instantiation.  

We can remove precached attributes and only support bounded instruments.  This means you still pay the cost of creation when a single attributeset can be used for multiple instruments. This isn't theoretical, for example every packet we receive uses the same attribute set for the "bytes received" counter and the "packet count" counter.  This means you can't do an LRU cache of attribute sets, so if your web server handles a request from a tenant it can cache tenant specific attribute sets assuming the load balancer will probably send another request for that tenant to the server again.  

We could make `AttributeSet` a trait with the current implementation in the SDK.  This would require annotating everything with a second generic trait, which may be complex with a lot of the `dyn Any` and other dynamic calls there are, at least without extra runtime costs.  It also has complexity in passing counters around, because the generic parameter can't be inferred in many circumstances due to it being used in a different area of code than its creation or the `measure` call.

**Comment by KallDrexx** [comment]
After talking with Cijo a bit, we came to the conclusion to revert the precached attribute set work, pause the bound instruments API, and add the concept of instrument level attributes at instrument (e.g. counter) creation time.  I'll investigate what that will look like.

**Comment by cijothomas** [comment]
SIG call:
1. Revert the PR before conflicts start appear. -- Matthew will send PR
2. Meter (instrumentation scope attributes) or instrumentation attributes needs to be explored to see if it can indeed achieve the high perf.
               * Might need special casing 0 attributes case.  - Matt/Cijo will explore this, and send PRs.
               * View might complicate things, but maybe not.. need to explore. - Cijo will explore this.
