### ISSUE TITLE
Metrics API - Move to builder pattern for creating Meters

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-rust#2164]
Related to https://github.com/open-telemetry/opentelemetry-rust/issues/1527, but for Metrics
This is part of Metrics API, and hence must be done by Metrics API RC.

**Comment by stormshield-fabs** [comment]
This was made a bit more complicated with the object-safety requirement on `MeterProvider` added in https://github.com/open-telemetry/opentelemetry-rust/pull/2112/

The problem is mostly about ergonomics because we probably can't have an API similar to the other signals. 

I don't think we want to re-introduce `ObjectSafeMeterProvider`, since we would not be able to forward the builder method anyway, but a solution could be to have a "standalone" `MeterBuilder` (without the `MeterProvider::meter_builder` method).

**Comment by cijothomas** [comment]
@utpilla can you help with this?

ALso https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/src/common.rs#L413 is something we want to remove from `opentelemetry` crate. (okay to be in sdk crate)
