### ISSUE TITLE
Missing documentation for opentelemetry-otlp crate on docs.rs

### ISSUE THREAD

**Issue by drexler** [open-telemetry/opentelemetry-rust#387]
Link: https://docs.rs/crate/opentelemetry-otlp/0.3.0

**Comment by TommyCpp** [comment]
hmm, it indicates we are trying to create proto files in src dictionary. Looks like we were trying to build files with grpcio in src. We should build it into OUT_DIR instead. 
https://github.com/open-telemetry/opentelemetry-rust/blob/c56866bb6152a2ffe8310b8c17a22d07189047a0/opentelemetry-otlp/build.rs#L42

**Comment by imox2** [comment]
@TommyCpp 
Cargo exposes OUT_DIR environment variable to your crate when it is compiled.  

OUT_DIR — If the package has a build script, this is set to the folder where the build script should place its output.

We can use this but then I think we will also have to use OUT_DIR to provide path for include compiled rust files in src/proto.rs?

**Like:**
```
pub(crate) mod grpcio {
    include!(concat!(env!("OUT_DIR"), "/common.rs"));
}
```

**Instead of**:
```
pub(crate) mod grpcio {
    pub(crate) mod common;   
}
```

**Comment by TommyCpp** [comment]
@imox2 I think `grpc-io` generates an organized module instead of just files(like tonic does). So we could just match that module path. But yeah we probably shouldn't leave the generated file at the root of OUT_PUT path.

Also, I think this issue has been fixed when we added support for tonic, the [current version](https://docs.rs/crate/opentelemetry-otlp/0.5.0) can build doc without errors.

**Comment by jtescher** [comment]
Working currently https://docs.rs/opentelemetry-otlp/
