### ISSUE TITLE
PipelineBuilder::install & Uninstall APIs are error prone

### ISSUE THREAD

**Issue by danburkert** [open-telemetry/opentelemetry-rust#427]
When `Uninstall` drops it disables trace collection, which forces callers to use `mem::forget` in instances where global trace collection is enabled in a function other than `main`.  The [primary example](https://github.com/tokio-rs/tracing/blob/master/examples/examples/opentelemetry.rs) I've found of using opentelemetry-jaeger does not point this out, and it can be very difficult to debug why traces are not being collected when basing code off that example and moving it into a new function.

**Comment by danburkert** [comment]
Couple more thoughts:

The `#[must_use]` annotation on `Uninstall` is worthless, since most callers will use the results of `build` since they need the tracer, but the `Uninstall` is frequently not used, as in this example: https://github.com/open-telemetry/opentelemetry-rust/blob/master/examples/tracing-grpc/src/server.rs#L48-L50.

Can the lifetime of trace collection be tied to the tracer instead of having a separate `Uninstall?

**Comment by jtescher** [comment]
@open-telemetry/rust-approvers this does seem to be a common footgun for people coming to otel. Thoughts on alternative span flushing strategies? Could think about #364 in relation to this as well.

**Comment by djc** [comment]
As I recall, the uninstall return widget thing was added relatively recently, do you remember why/what problem it solved? It did strike me as pretty surprising (and looking at my own code, it might have similar issues).

**Comment by jtescher** [comment]
It is currently used as the mechanism to shut down the batch span processor so the current batch is sent before the process exists. This is currently done when the tracer provider is dropped and as it is often registered as a global, the uninstall guard deregisters the global.

Alternatives could include a better way of accomplishing this "send spans async before process exit" behavior, or simply requiring folks to coordinate themselves via a manual call to [force_flush](https://github.com/open-telemetry/opentelemetry-rust/blob/aae3f4efd013bb2b6bc1481abc4f03810f2a5386/opentelemetry/src/sdk/trace/span_processor.rs#L81) (footgun for some data loss, but maybe acceptable).

**Comment by TommyCpp** [comment]
IMHO we can implement [the `shutdown` method for `Provider`](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#shutdown) and ask the user to shut down the provider explicitly. Furthermore, we can use Procedural Macros to shut down for users. For example 
```rust
#[shut_down_trace_provider] // this will invoke shut down at the end of the main function
fn main() -> {
    // do something
}
```

**Comment by frigus02** [comment]
Agree with footgun. It seems to be a constant point of surprise. Requiring folks to manually call shutdown/force_flush might be less surprising.

I feel like we can't be the only ones with this problem. How are others solving this? Does Tokio have a similar situation? Isn't there a global runtime that has to exist? Otherwise certain functions panic. Options for the developer are:

- A macro on main
  
  ```rust
  #[opentelemetry::main(need_to_configure_everything_in_env_vars)]
  fn main() {}
  ```

- Execute main program logic in tokio controlled callback

  ```rust
  opentelemetry_jaeger::new_pipeline()
      .with_option1()
      .run(async {
          // main logic
      });
  ```

Would any of that work for us?

**Comment by djc** [comment]
A tokio runtime will shutdown when you drop the `Runtime`. The problem here is that we get two return values, one of which is apparently *only* used to shut it down. A tokio `Runtime` can also be manipulated (but not shut down, apparently) by getting a `Handle` on it through `Handle::current()`, maybe something like that would be a viable option. Why aren't we coordinating shutdown through the resulting tracer? Because it is given "away" to the subscriber registry?

**Comment by frigus02** [comment]
> Why aren't we coordinating shutdown through the resulting tracer?

I think that's mainly because you can have multiple tracers for the same tracer provider. The tracer provider is supposed to do the final shutdown if I remember correctly.

> Because it is given "away" to the subscriber registry?

The integration with `tracing` is possibly a separate discussion. When you're using `tracing` you probably don't need the globally registered tracer provider. Because `tracing` comes with it's own globally registered subscribers. Would it make sense to give the entire TracerProvider to `tracing-opentelemetry`? That would mean however, that `tracing` needs to have a way to flush the remaining spans when the program exits. Does this exist?

> A tokio Runtime can also be manipulated (but not shut down, apparently) by getting a Handle on it through `Handle::current()`

The corresponding thing here would be the TracerProvider. You can get a handle to the globally registered one through [`global::tracer_provider()`](https://docs.rs/opentelemetry/0.11.2/opentelemetry/global/fn.tracer_provider.html).

Maybe the least surprising pattern would be that you have to call sth like `global::tracer_provider().shutdown()` at the end of `main` to flush the remaining spans.

**Comment by jtescher** [comment]
Requiring the user to call a function is certainly an option, e.g. go has pipelines return a flush method https://github.com/open-telemetry/opentelemetry-go/blob/0df8cd620c46567b38a70f1f1a8e968d0a806c06/example/jaeger/main.go#L33.

**Comment by djc** [comment]
> Maybe the least surprising pattern would be that you have to call sth like `global::tracer_provider().shutdown()` at the end of main to flush the remaining spans.

That at least sounds like an improvement. Is "flushing the remaining spans" the goal of being able to uninstall the tracer?

And speaking of the tracing integration, I feel like some parts of the opentelemetry crate don't get used in the case of using tracing to collect spans. Maybe we should make that more clear in the API somehow, by clearly separating parts of the API that overlap with tracing from the other parts? This isn't quite clear to me.

**Comment by TommyCpp** [comment]
> Is "flushing the remaining spans" the goal of being able to uninstall the tracer?

I think the Uninstall in question is for TraceProvider. And when it drops, it replaces the current TraceProvider with the previous one(if there isn't one available, use no-op TraceProvider). Since the current TraceProvider will then out of scope. It will be dropped and calling the `shutdown` method on all of its processors, which will flush all remaining spans.

If we are going to get rid of Uninstall and TraceProviderGuard, should we just revert the TraceProvider to the previous one when the TraceProvider been dropped?

**Comment by jtescher** [comment]
Yeah as @TommyCpp said it facilitates shutting down the SDK. Basically we want a way to make sure that the behavior defined in the [`SpanProcessor::shutdown` spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#shutdown-1) and [`Exporter::shutdown` spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#shutdown-2) are called. 

We currently have span processor / exporter shutdowns executed when the tracer provider is dropped to ensure this happens and the associated cleanup happens before the process exits, but there are a few challengs: 

1. the cleanup code is often async, which means issues with blocking and the potential deadlocking described in #364. 
1. In the common case where the tracer provider is registered globally, we need a way of knowing when to un-register in order for the drop logic to run before any async runtime is shutdown (hence the uninstall guard) but this is the footgun. 
1. in the less common case where a user sets up a tracer provider themselves and doesn't register it as a global, it can _also_ be dropped early, leading to unintentional shutdown.

We could resolve some of the accidental shutdown issues by removing the drop guard and requiring the tracer provider be manually shut down, this may also allow multiple shutdown strategies, or other ways of simplifying supporting apps that have async runtimes and apps that do not.

> And speaking of the tracing integration, I feel like some parts of the opentelemetry crate don't get used in the case of using tracing to collect spans

The main difference is that `tracing-opentelemetry` introduces a [PreSampledTracer](https://docs.rs/tracing-opentelemetry/latest/tracing_opentelemetry/trait.PreSampledTracer.html) trait, allowing it to makes sampling decisions before spans get created. The linked docs explain why in a little more detail, but tracing requires that trace ids can be assigned _after_ span creation which the otel API does not allow directly. Other than that it is mostly just mapping the tracing api to the otel span builder which is a normal / supported way of interacting with otel. (The main pain points are in the mapping the "active span" globals between the two systems, e.g. if you mark a span as active in otel it will not be tracing's `Span::current`, and vice versa so the boundaries between systems that want to be able to extract / inject become more complicated / error prone)

**Comment by TommyCpp** [comment]
Please correct me if I am wrong @jtescher. In the current implementation, `TraceProviderGuard` also helps maintain a stack of TraceProvider, when `TraceProviderGuard` drops, it reset the global trace provider to the previous one. For example

```rust
fn main() -> {
   let outer_provider = ...;
   let outer_guard  = global::set_tracer_provider(out_provider);
   // here the global provider is outer_provider
   {
        let inner_provider = ..;
        let inner_guard = global::set_tracer_provider(innter_provider);
        // current global provider is inner_prodier;
   }
   // when inner_guard drops, it set global provider back to outer_proder
}
```
The problem this issue describes is that when you set_tracer_provider in a function. It won't send any spans. I would guess the reason is the tracer provider gets dropped at the end of the function. And the tracer provider in main function will be set to noop.

Maybe we should only manage one global tracer provider and ask users to manage the result themselves. And we can run clear up code when the global tracer provider is dropping?
