### ISSUE TITLE
batchexporter doesnt export spans when batch size is reached 

### ISSUE THREAD

**Issue by kstasik** [open-telemetry/opentelemetry-rust#468]
I think there are some issues with BatchExporter. We are using opentelemetry-otel on some services and we have huge gaps during high traffic testing:

Correct me if i'm wrong but in rust the only way of triggering export is interval:

https://github.com/open-telemetry/opentelemetry-rust/blob/v0.12.0/opentelemetry/src/sdk/trace/span_processor.rs#L277-L281

in golang when first batch is full it triggers export:

https://github.com/open-telemetry/opentelemetry-go/blob/9524ac095466565e01746600da3d83f27220a5da/sdk/trace/batch_span_processor.go#L213-L218

Please let me know if i'm correct - i will create PR with fix.

**Comment by kstasik** [comment]
What is more i didn't notice any indicator of number of spans dropped like:

https://github.com/open-telemetry/opentelemetry-go/blob/9524ac095466565e01746600da3d83f27220a5da/sdk/trace/batch_span_processor.go#L282

**Comment by kstasik** [comment]
why this pr has been closed, not merged? https://github.com/open-telemetry/opentelemetry-rust/pull/245/commits/f67c61255df91fb03b4ea0b28ad789a2cd4815b3

**Comment by djc** [comment]
You can read the PR discussion: https://github.com/open-telemetry/opentelemetry-rust/pull/245.

**Comment by kstasik** [comment]
@djc shouldn't behaviour of sdk be unified across opentelemetry libs in all languages if it's possible? I think i understand @jtescher arguments but can changing it be reconsidered?

Currently there is no possibility in rust to increase frequency of publishing spans when traffic increases (but there are 
possibilities to protect collector from high load/decrease traffic like sampling).

Right now same environment variables will trigger completely different opentelemetry behavior  in applications written in different languages, am i right?

**Comment by TommyCpp** [comment]
Hi, [the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#batching-processor) isn't clear about when should the batch span processor export the spans. 

As for the implementation here, we could keep the `max_queue_size` so that the buffered spans won't cause OOM and export the spans when the size of queue reaches the `max_export_size`. I think the main reason #245 closed was it removed the limit on the size of the buffer, which put the application in danger of OOM. 

I think the other problem here if we want to send more requests is that the current implementation blocks adding spans in the buffer before the last export returns, that may slow the application or cause spans being dropped when the latency is high

**Comment by TommyCpp** [comment]
@jtescher @djc Do you guys think it's reasonable we change the BatchSpanProcessor to:
- Move the buffer into BatchSpanProcessor
- Only use the background task to export spans.
- Have an upper limit on the channel between BatchSpanProcessor and the background task. If there are too many spans, drop(or allow users to config the behavior, just in case someone want to block and wait)
- Send the spans when the buffer reaches the `max_export_size` or it hits scheduled delay(Will need to reset the countdown after each export of course)

The current version, BatchSpanProcessor basically does nothing but send spans or other commands into the channel. The background tasks handle adding spans into the queue and export the spans.

**Comment by djc** [comment]
It sounds like an improvement to me!
