### ISSUE TITLE
`opentelemetry::global::shutdown_tracer_provider()` Hangs indefinitely, and other troubles

### ISSUE THREAD

**Issue by Sushisource** [open-telemetry/opentelemetry-rust#536]
Hello,

Been trying to get tracing exporting going to either Jaeger or Zipkin, and with both I'm running into issues actually getting much exported.

Following the readme for either, they mention to call `global::shut_down_provider(); // sending remaining spans` on exit (which, the Readmes seem to be outdated). Calling what looks like the current equivalent (in the title) just locks up entirely. I'm using opentelemetry with the `rt-tokio` feature, and both the Jaeger and Zipkin crates, with or without their `tokio` features, exhibit this behavior.

When I don't call this and instead do something silly like just sleep for a while at the end of a test, I'll get output like:
```
OpenTelemetry trace error occurred ExportFailed(ThriftAgentError(ProtocolError { kind: SizeLimit, message: "jaeger exporter payload size of 248781 bytes over max UDP packet size of 65000 bytes. Try setting a smaller batch size." }))
OpenTelemetry trace error occurred ExportFailed(ThriftAgentError(ProtocolError { kind: SizeLimit, message: "jaeger exporter payload size of 112387 bytes over max UDP packet size of 65000 bytes. Try setting a smaller batch size." }))
OpenTelemetry trace error occurred Other(TrySendError { kind: Disconnected })
OpenTelemetry trace error occurred Other(TrySendError { kind: Disconnected })
```

Somehow I had Jaeger exporting working OK before (never with `opentelemetry::global::set_text_map_propagator(opentelemetry_jaeger::Propagator::new());` or the shutdown call), but when trying to run a much larger scale load test I was never able to collect anything because of the packet size limits. The error helpfully suggests I try setting a smaller batch size, but I was totally unable to determine how to do that after reviewing the docs for a while.

Thanks for the hard work on this crate  -- my honest feedback is that the API is pretty challenging to figure out. Taking something like the above batch size problem, I can find https://docs.rs/opentelemetry/0.13.0/opentelemetry/sdk/trace/struct.BatchSpanProcessorBuilder.html#method.with_max_export_batch_size which looks like it might be what I want, but I can't actually find any way to use that in combination with the Jaeger exporter.

Thanks again! Let me know if I can provide more info or feedback.

**Comment by TommyCpp** [comment]
Thanks for the feedback. We try to adapt the builder pattern for every configuration we encounter. But there are many configurations so it can be confusing.

To your questions. I think what you are looking for is [`with_max_packet_size`](https://docs.rs/opentelemetry-jaeger/0.12.1/opentelemetry_jaeger/struct.PipelineBuilder.html#method.with_max_packet_size). I think in the future we could introduce include the component that throws the error in error messages. May help identify where to look at.

As for the `shutdown_tracer_provider` hang forever. Could you provide more information on what's your runtime looks like. Is it tokio current thread or multiple thread scheduler?

**Comment by Sushisource** [comment]
Thanks @TommyCpp  -- So setting `with_max_packet_size` just lets me hit that error with smaller values, but it doesn't seem to fix the problem of actually allowing me to tell the batch exporter to send smaller batches.

For the hang, I'm using tokio with the multiple thread scheduler. I tried zipkin with and without `reqwest-client` and both hung, and jaeger hung with `tokio` set or not.

**Comment by jtescher** [comment]
@Sushisource you can also use the `OTEL_BSP_MAX_EXPORT_BATCH_SIZE` env var to export in smaller batches https://github.com/open-telemetry/opentelemetry-specification/blob/5a19b53d71e967659517c02a69b801381d29bf1e/specification/sdk-environment-variables.md#batch-span-processor

**Comment by simon-an** [comment]
Same issue here. 

In my case it is a combination of 

```rust
#[actix_web::main] 
.with_client(reqwest::Client::new())
.install_batch(opentelemetry::runtime::Tokio);
```

**Comment by TommyCpp** [comment]
> For the hang, I'm using tokio with the multiple thread scheduler. I tried zipkin with and without `reqwest-client` and both hung, and jaeger hung with `tokio` set or not.

Could you provide an example if it's possible. I ran some examples and it seems to be working. Wondering if I missed something here. Thanks in advance.

**Comment by Sushisource** [comment]
@TommyCpp This repros it consistently for me:  https://gist.github.com/Sushisource/0c04fcc0fecef386a46cd6dd25c7a296

**Comment by TommyCpp** [comment]
> Same issue here.
> 
> In my case it is a combination of
> 
> ```rust
> #[actix_web::main] 
> .with_client(reqwest::Client::new())
> .install_batch(opentelemetry::runtime::Tokio);
> ```

@simon-an May be try `runtime::TokioCurrentThread`?. I think the `actix_web` uses tokio current thread runtime by default.

**Comment by Sushisource** [comment]
@TommyCpp Ah, sure this makes sense and fixes it. It would be really great if the examples (READMEs like the one [here](https://github.com/open-telemetry/opentelemetry-rust/tree/main/opentelemetry-jaeger))  mentioned that using a multithreaded runtime, or setting the current thread batch executor is necessary to avoid blocking - I think probably a lot of people are going to try using the library via tests like this when they first try it out and (obviously, lol) this can be a confusing thing to run into.

Thanks for the help! Feel free to close this issue, really appreciate it.

**Comment by simon-an** [comment]
@TommyCpp  Don't I have the multithreaded runtime, when i have a toml like this?

```toml
actix-http = { version = "3.0.0-beta.6", default-features = false, features = ["compress"] }
actix-web = { version = "4.0.0-beta.6", default-features = false, features = ["compress"] }
actix-web-opentelemetry = { version ="0.11.0-beta.3", features = ["metrics"] } 
tokio = { version = "1.5", features = ["rt-multi-thread", "macros", "time"] }
```
You are right. It works when i use 

`
opentelemetry::runtime::TokioCurrentThread
`

instead of 

`
opentelemetry::runtime::Tokio
`

[example project](
https://github.com/simon-an/rust-opentelemetry-examples)

**Comment by TommyCpp** [comment]
> @TommyCpp Don't I have the multithreaded runtime, when i have a toml like this?

I believe the `actix_web` is actually [running on a tokio current thread scheduler by default](https://actix.rs/actix-web/actix_web/rt/struct.Runtime.html).

**Comment by simon-an** [comment]
@TommyCpp i found a solution and updated the example project.

```rust
    Handle::current().spawn_blocking(move || {
        opentelemetry::global::shutdown_tracer_provider();
    }).await.unwrap();
```

Thanks for pointing out, that there might be a current thread scheduler in a multithreaded runtime. That was not that clear to me.

**Comment by Geal** [comment]
I see a similar bug in [Apollo router](https://github.com/apollographql/router), running on the tokio multi threaded runtime, in the main code, not in tests. Reproduction info is [here](https://github.com/apollographql/router/issues/331).

The exporter is created [here](https://github.com/apollographql/router/blob/79b1596509ecff09968f4bd6afaebff6d98709d9/apollo-router/src/trace.rs#L47-L77).

The fix proposed by @simon-an [works](https://github.com/apollographql/router/blob/79b1596509ecff09968f4bd6afaebff6d98709d9/apollo-router/src/trace.rs#L74-L77), but I took some time to dig a bit more into it.

It happens when we try to reload the configuration and create a new subscriber. We need to replace the tracer provider because we might switch to a different exporter (I feel there's another way to do that without replacing the tracer provider but couldn't find it)
It hangs when the `try_initialize_subscriber` function drops the result of `set_tracer_provider`, and I tracked it down to `BatchSpanProcessor::shutdown`:

https://github.com/open-telemetry/opentelemetry-rust/blob/a81c6c6e6c1d9c5a0def5384b5c6291bb56f0f18/opentelemetry/src/sdk/trace/span_processor.rs#L266-L275

That function is called because the `TracerProvider` calls shutdown on all its tracers on drop.

Through generous println applications, I see that timeline:
- `set_tracer_provider` is called
- `TracerProvider` is dropped
- `BatchSpanProcessor::shutdown` is called. At this point the batch task is still running fine, regularly receiving flush messages from the [ticker](https://github.com/open-telemetry/opentelemetry-rust/blob/a81c6c6e6c1d9c5a0def5384b5c6291bb56f0f18/opentelemetry/src/sdk/trace/span_processor.rs#L301-L303)
- the shutdown function sends the shutdown message
- the shutdown function [blocks on the receiver](https://github.com/open-telemetry/opentelemetry-rust/blob/a81c6c6e6c1d9c5a0def5384b5c6291bb56f0f18/opentelemetry/src/sdk/trace/span_processor.rs#L271-L273). It hangs at this point. The batch task does not receive any new message, which is very surprising (the ticker should continue to send)
- then the new batch task from the new tracer provider spawns and starts receiving  flush messages from the ticker

I suspect a bad interaction between the tokio runtime and the futures executor. I tried replacing it with a call to tokio's `block_on`, but then I get a panic because I am trying to start a new tokio runtime from inside an existing runtime.

This is not a blocking bug for us, as I said the proposed fix works. But it would be nice to get a good fix inside the opentelemetry crate, and I hope I gave enough context to help in fixing it :slightly_smiling_face:

**Comment by Oliboy50** [comment]
Can we know here when someone will take the time to fix this issue helped by [what Geal said](https://github.com/open-telemetry/opentelemetry-rust/issues/536#issuecomment-1018604343)? 

Just so we know when we will be able to remove our workaround 🙏

**Comment by Oliboy50** [comment]
🆙 🙏 Like [Geal said](https://github.com/open-telemetry/opentelemetry-rust/issues/536#issuecomment-1018604343):
> it would be nice to get a good fix inside the opentelemetry crate

Because it's currently painful to implement a wrapper around the opentelemetry crate, moreover since we don't have `AsyncDrop` yet (having to execute an `async` workaround in a `impl Drop` is not that easy).
