### ISSUE TITLE
Self-recursive debug implementations

### ISSUE THREAD

**Issue by tustvold** [open-telemetry/opentelemetry-rust#550]
I'm not sure how widespread this is, but if you try to debug print a prometheus sync instrument it leads to a stack overflow. Or if you debug print with `{:#?}` it effectively deadlocks trying to print an infinite string, I suspect you would get a stack overflow eventually if you left it for long enough.

The code snippet below demonstrates this problem, it overflows the stack

```
let exporter = opentelemetry_prometheus::exporter()
            .with_resource(Resource::new(vec![KeyValue::new("R", "V")]))
            .init();

let provider = exporter.provider().unwrap();
let meter = provider.meter("foo", None);
let counter = meter.f64_counter("test").init();
counter.add(23., &[KeyValue::new("foo", "bar")]);

println!("{:?}", counter);
```

**Comment by TommyCpp** [comment]
Looks like the reason is [`Instrument`](https://github.com/open-telemetry/opentelemetry-rust/blob/88e779d53e43d161bb0703808d47728f2fb54a14/opentelemetry/src/sdk/metrics/mod.rs#L516-L520) refers to [`Accumulator`](https://github.com/open-telemetry/opentelemetry-rust/blob/88e779d53e43d161bb0703808d47728f2fb54a14/opentelemetry/src/sdk/metrics/mod.rs#L73-L73), which contains references to [`AsyncInstrument`](https://github.com/open-telemetry/opentelemetry-rust/blob/88e779d53e43d161bb0703808d47728f2fb54a14/opentelemetry/src/sdk/metrics/mod.rs#L377-L381). And `AsyncInstrument` also contains a reference to `Instrument`, creating a loop.

**Comment by TommyCpp** [comment]
close via #552
