### ISSUE TITLE
Are the examples up-to-date? basic-otlp-http example not working

### ISSUE THREAD

**Issue by evergreen-trading-systems** [open-telemetry/opentelemetry-rust#594]
I was following the example here https://github.com/open-telemetry/opentelemetry-rust/blob/main/examples/basic-otlp-http/src/main.rs, but my program doesn't compile.

`tracing` here https://github.com/open-telemetry/opentelemetry-rust/blob/main/examples/basic-otlp-http/src/main.rs#L13 appears nowhere to be found in the docs https://docs.rs/opentelemetry-otlp/0.8.0/src/opentelemetry_otlp/lib.rs.html#251.

I know the `config.toml` https://github.com/open-telemetry/opentelemetry-rust/blob/main/examples/basic-otlp-http/Cargo.toml is using the local package while I am using the package hosted at crates.io. Could it be mismatched versions?

**Comment by evergreen-trading-systems** [comment]
No, it hasn't been updated as shown https://docs.rs/opentelemetry-otlp/0.8.0/src/opentelemetry_otlp/lib.rs.html#175 but in GitHub https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-otlp/src/lib.rs#L175

**Comment by evergreen-trading-systems** [comment]
I was exploring opentelemtry-rust as a tracing solution for my Rust software but I don't think it's production-ready, not like [Vector](https://github.com/timberio/vector/issues/790).

Now I'm exploring just tracing, exporting to file and ingest through Vector or directly to Jaeger in case anybody is doing something similar.

**Comment by TommyCpp** [comment]
Yes, we are still working towards GA on the tracing part now, the opentelemetry-collector is also in pre 1.0 status. The examples in the main branch use the main branch's code rather than the latest released code. There was a change introduced to allow the OTLP pipeline to send metrics and tracing info to the collector. https://github.com/open-telemetry/opentelemetry-rust/pull/585.

Examples that use the latest released version can be found [here](https://github.com/open-telemetry/opentelemetry-rust/tree/133ab27744776134eeee798a442f23a291571f6e/examples)
