### ISSUE TITLE
jaeger: thrift agent failed with message too long

### ISSUE THREAD

**Issue by RustPanda** [open-telemetry/opentelemetry-rust#676]
Hi. I have this problem too #648 . trace is collecting too much data, I get this error when submitting.
I don’t understand the behavior of open-telemeter-yaeger, I don’t understand and cannot believe that the parcel will be sent successfully even if the batch size is reduced.
I had to set OTEL_BSP_MAX_EXPORT_BATCH_SIZE = 25

I want someone to pay attention to this issue so you can control it

**Comment by 0xpr03** [comment]
@RustPanda I just use
```rust
// https://github.com/open-telemetry/opentelemetry-rust/issues/676
    std::env::set_var("OTEL_BSP_MAX_EXPORT_BATCH_SIZE", "25");
```
for now.

**Comment by TommyCpp** [comment]
IIRC the problem is [the UDP has a limit on packet length](https://stackoverflow.com/questions/1098897/what-is-the-largest-safe-udp-packet-size-on-the-internet). You can try to set auto split to true to ask the exporter to split the batch to multiple UDP packets https://github.com/open-telemetry/opentelemetry-rust/blob/615d7f52e1d987cc2028e42096d1e600ab366cc7/opentelemetry-jaeger/src/exporter/mod.rs#L259-L262

It will have a performance impact and if you have a span that cannot fit into one single UDP packet(It should be rate but sill possible). You will still get an error.

**Comment by TommyCpp** [comment]
With[ opentelemetry-jaeger v0.16 release](https://docs.rs/opentelemetry-jaeger/0.16.0/opentelemetry_jaeger/). The `with_auto_split_batch` method should be available.
