### ISSUE TITLE
Risk of `update_name`

### ISSUE THREAD

**Issue by rex-remind101** [open-telemetry/opentelemetry-rust#725]
I'm hoping to leverage `update_name` for GraphQL so that after the GraphQL query is parsed I can update the root span name of the trace to the OperationName of the GraphQL query we're tracing over. However, update_name comes with a caveat documented here https://github.com/open-telemetry/opentelemetry-rust/blob/561426e4d5e04fff10f896c681c7501adbe95929/opentelemetry/src/trace/span.rs#L156

However, reading this it's unclear if this is introducing a "performance reasons" issue or a correctness issue. If this affects the correctness of spans that seems like a non-starter and should be called out. If the results are correct but we sacrifice some performance that may be ok. It's also unclear how much performance is sacrificed - phrasing this in terms of big O would be helpful for evaluation.

Another option would be to not rely on the root span name as the primary operation name in DataDog, however, this seems broken as soon as I switched to `install_batch`, which I would assume is a much larger performance concern than using `update_name`. That issue is documented here https://github.com/open-telemetry/opentelemetry-rust/issues/674#issuecomment-1033287483 .

**Comment by TommyCpp** [comment]
We should probably update the doc to be in line with the specs. But the caveat here is when spans are created usually a [sampler](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#sampler) will decide whether or not to keep these spans. It can leverage all information available at that time including the span name. If you change the span name after it will not change the decision whether to sample it or not. 

If you don't rely on the span name for sampling then it should be fine. Otherwise, it could be confusing.

**Comment by rex-remind101** [comment]
Thank you, we have sampling on the side of DataDog but that's upstream. I'm assuming this Sampler is an actual structure one would need to instantiate for opentelemetry-rust?

**Comment by TommyCpp** [comment]
Sorry for the late reply. I was referring to [ShouldSample](https://github.com/open-telemetry/opentelemetry-rust/blob/9f3abedd1c54abcf7326918d4dccb85ddc4d6cf0/opentelemetry/src/sdk/trace/sampler.rs#L51-L64) trait. The Sampler enum is a set of buildin sampler
