### ISSUE TITLE
Change sampling decision on error

### ISSUE THREAD

**Issue by rex-remind101** [open-telemetry/opentelemetry-rust#726]
We would like to always sample on error, but I was unable to find an example of how to do this. Is there a way to do this? Can we change a sampling decision dynamically?

**Comment by TommyCpp** [comment]
SDK's build-in sampling only happens before span creates. You can wrap the span exporter to add additional sampling logic in [export](https://github.com/open-telemetry/opentelemetry-rust/blob/dc7d81fdfa9b99bf78f73724f81d3b1635b975cf/opentelemetry/src/sdk/export/trace/mod.rs#L40) method. Simply examine the spans and drop the ones you don't want. 

However, distributed tracing often runs across different applications. Please use cautiously on your sampling rule so that you don't have a gap in distributed tracing. See [sampling](https://github.com/open-telemetry/opentelemetry-rust/blob/dc7d81fdfa9b99bf78f73724f81d3b1635b975cf/opentelemetry/src/sdk/export/trace/mod.rs#L40) for details.
