### ISSUE TITLE
Prometheus and Pushgateway

### ISSUE THREAD

**Issue by kudlatyamroth** [open-telemetry/opentelemetry-rust#981]
Is there a way to push opentelemetry-prometheus metrics with pushgateway?
I don't see example with this...

few versions back there was config for host and port, so i think that there was some way to do that?

**Comment by hdost** [comment]
As I alluded to on gitter, the current tooling does not support push gateway. Technically, it's not even part of the specifications, but metrics right now in general, are considered alpha for rust.

**Comment by cijothomas** [comment]
You can use OTLP Exporter today to export metrics to Prometheus (instead of pull/scrap). This is a recent addition to Prometheus product.

OTel .NET has an example showing this. I hope to get a similar example for OTel Rust repo too!
https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/metrics/getting-started-prometheus-grafana#install-and-run-prometheus

**Comment by hdost** [comment]
It should be noted that Prometheus directly ingesting OTLP is still only available as a feature flag but progress can be tracked here https://github.com/prometheus/prometheus/milestone/12.

**Comment by cijothomas** [comment]
Closing as not planned. Let us know if you need further help.
